### ISSUE TITLE
SCN Regex

### ISSUE THREAD

**Issue by AlanBridgeman** [BCLibCoop/nnels-pipeline-gadget#2]
In order to recognize if a file is named with just the SCN, SCN_title or follows a valid title_SCN format I need some form of a regular expression to test for a valid SCN so that if I parse something that matches that then i can search the tab separated file for that SCN I could do this for all entries but its a bit wasteful to do that especially given that I think there is some kind of regex we can come up relatively easily. False positives are fine given that I'm still querying the file its more the opposite (where we don't recognize something as a SCN even though it is) that I'm more worried about.

**Comment by AlanBridgeman** [comment]
I mean I guess one option could be to do it the opposite way so that I go through the tab separated list and compare the SCNs to the filename but that still seems a little wasteful given that you'd have to loop through the n entries of the tab separated a minimum of m times where m is the number of files your checking. so in theory it would n*m checks but thats given that a few other variables aren't applicable because the way I'm parsing it is tokenizing the string by underscores(_) so then if a title had more than one word seperated by underscore than the asymptotic running time would even be multiplieed by a third variable of how many words per filename there were.

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Interesting, thanks for working out the performance considerations here and your work thus far.

Regarding a regex pattern for SCN, I expect the pattern will be different for each Provider or even each set of files. If we can get close to a "cookbook" of suggestions for the common patterns from existing Providers that would easily cover 3/4 of the files we receive.

(We will always be dealing with a given set at a time rather than all possible files, and to their credit there is a low amount of internal variability in these schemes).

I'm OK with having to manually specify that pattern at runtime. If it does end up not recognizing the SCN in a 'false negative' scenario, well hopefully we we checking in dry-run mode first 😁 
Some manual cleanup of a few erroneous files, such as two SCNs concat'd by mistake is to be expected.

I think offloading that regex pattern to the user side-steps the cases where there would otherwise be potential multipliers by the number of tokens formed. Mainly due to not having to cover all possible cases at once. What do you think?

Towards that end, I've added some blank files for test cases I found trawling the S3 bucket in 5fabf4dab2483932159d51cc4f246abb09f278bf - note the ones specifying the DAISY format before the file extension - useful to preserve that hint.

**Comment by AlanBridgeman** [comment]
@gitschatz I do agree with you about maybe offloading some of this to the front end user but my . question being is it expected that they write a full regular expression themselves or rather that they provide some version of "training data" and we figure out a regex from that? or am I misunderstanding

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Ah, I gotcha—I think I will be the primary user of the tool but future-proofing is always worth it. 

Perhaps a few options: a handful of regexes matching common patterns and then an option for custom. 

What form would the training data take in the CLI interface? That might be neat but hard to pull off.

Further, we should be validating the regex against the files found in the specified path (--dictionary in this case I believe) before doing any renaming. Does that help?

**Comment by AlanBridgeman** [comment]
@gitschatz Actually that makes a really good point I hadn't considered. Because ultimately if the pattern didn't validate against at least one of the entries in the dictionary than it obviously is useless for for this purpose (the purpose being we need to parse SCNs potentially in the dictionary out of filenames).

I get what you mean about a standard one and an option for custom ones thought this brings me to a question of how automated do you want it versus CLI oriented? Which may seem like a question you can say both to but part of the problem is a CLI tends to be3 "vent driven and happen when a user perofrms an action automation normally happens when it can. As an example do you want to manually trigger the script to create a new dictionary or would you prefer me to register an inotify listener on the filesystem to listen for a .xml fil creation event say. It also just has some impacts on how I design the functions (spend the time to validate the input that kind of thing)

Quickly just touching on this "training data" idea; I think its interesting because potentially you could use the SCNs in the dictionary. I know it sounds challenging and difficult (and it probably is) but my suspicion is that might be common enough that someone might have created a library or something to do it just thought it might be an option to consider. I just thought taking a few moments to look into it might save us time in the long run.

I hope thats all clear

**Comment by AlanBridgeman** [comment]
So, I've been looking into an Aho–Corasick algorithm implementation as I think its the best solution for this problem given it acts like a character-by-character state machine.

 https://en.m.wikipedia.org/wiki/Aho–Corasick_algorithm

**Comment by OnGitHubSchatz** [comment]
> how automated do you want it versus CLI oriented

Fairly CLI-oriented. Only the rote parts such as renaming files and inserting generated SCNs should be automated, but still triggered by specific options and commands. I expect to have to write some regex from time-to-time, check with dry-runs, revise.

> As an example do you want to manually trigger the script to create a new dictionary or would you prefer me to register an inotify listener on the filesystem to listen for a .xml fil creation event say

The former for sure with a CLI option. XML record sets will usually be just part of the payload rather than from scratch.

The string matching algorithm is neat (I think I almost understand it) - any Python implementations readily available? Do you intend to use for both title/SCN matching? I don't follow how it would apply to defining a file naming scheme.

**Comment by AlanBridgeman** [comment]
@gitschatz Okay that whole CLI thing makes a lot of sense just needed to clarify so that I can make some clear design decisions.

Addressing the questions, the theory is that implementing the algorithm would enable me to parse a SCN out of a filename that might look something like
junkscn34566467_title.epub
where scn34566567 is the SCN rather than my current scheme which would try junkscn34566567. It does try to mach by title as well though I think 9/10 circumstances the SCN will be more successful because you could have a title
my_book.zip
my_book2.zip
my_book2_revision1.zip
as well a title is not unique which I understand at SCNs are at least for the context of the MarcXML files we are parsing. The Aho-Corrasic could address the issue of the three examples above for titles but again if there are multiple books with the same title that could play havick with the system a bit so 9/10 times I'm using the SCN

I could go into more depth about this but I'm not sure how much your looking for in terms of explination

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman 

Thanks, that is very clear to me now, especially where non-numeric characters are present at the ends of the SCN. I expect we will see underscore delimiters most of the time.

Anything for me to test after the recent refactoring?

**Comment by AlanBridgeman** [comment]
@gitschatz Not quite yet. But I'm almost done adding a whole OOP part to the scripts (as I realized I needed to check the SCN and title independently of order but aware of one another) which should put me pretty close to having something functional.

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman OK no worries - ping me if I seem to disappear for a bit - been busy elsewhere.
