### ISSUE TITLE
Testing rename operations

### ISSUE THREAD

**Issue by OnGitHubSchatz** [BCLibCoop/nnels-pipeline-gadget#6]
Now that rename executes for me, I notice func_rename doesn't get into the business of renaming the files in the testdata yet:

```
$ python2.7 cli.py -d output.txt -p '[0-9]+_.*' -t 'testdata'
Opening <type 'file'>
What would you like to do?: rename
Using augmented pattern: .*/[0-9]+_.*
find testdata -regextype posix-extended -regex '.*/[0-9]+_.*'
None
Tokens: [u'946062815', u'open', u'modernisms']
Do permutation stuff
Setting the SCN: 946062815
None
Tokens: [u'1001573653', u'DAISY202']
Setting the SCN: 1001573653
Changed book type to <BookFileType.DAISY202_Type object at 0x7fecf5f301d0>
None
Tokens: [u'944246088', u'Good', u'corporation', u'bad', u'corporation']
Do permutation stuff
Setting the SCN: 944246088
Setting the title: Good_corporation_bad_corporation
|----------------------------------------------------|
| BOOK SUMMARY
| ============
| File Path: testdata/files/946062815_open_modernisms.zip
| File Name: 946062815_open_modernisms.zip
| Book SCN: 946062815
| Book Title: None
| Book Type: None
|----------------------------------------------------|
|----------------------------------------------------|
| BOOK SUMMARY
| ============
| File Path: testdata/files/1001573653_DAISY202.zip
| File Name: 1001573653_DAISY202.zip
| Book SCN: 1001573653
| Book Title: None
| Book Type: <BookFileType.DAISY202_Type object at 0x7fecf5f301d0>
|----------------------------------------------------|
|----------------------------------------------------|
| BOOK SUMMARY
| ============
| File Path: testdata/files/944246088_Good_corporation_bad_corporation.zip
| File Name: 944246088_Good_corporation_bad_corporation.zip
| Book SCN: 944246088
| Book Title: Good_corporation_bad_corporation
| Book Type: None
|----------------------------------------------------|
```
These three books are present in my output.txt with both SCN and title, but 946062815_open_modernisms.zip 's Title isn't parsed and 1001573653_DAISY202's Title doesn't get looked up in the dict.

We also seem to not get past line 388 because Book SCN is set.

**Comment by OnGitHubSchatz** [comment]
(Created new issue for this instead)

**Comment by AlanBridgeman** [comment]
@gitschatz Just pushed a major code change should pull and take alook still needs some work but is significantly closer

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman cool, fixed an import there preventing execution.
Can you explain how to use it from CLI after these changes, I'm a bit confused.

**Comment by AlanBridgeman** [comment]
@gitschatz Thats actually a good questions, I haven't done a lot with the CLI I've mostly been concerned with the infrastructure surrounding it which is one of the reaaons the renaming still isn't quite implmented thought actively working on it. I guess the question is do you want an interactive CLI that prompts you for things or more of a flags based system? Also for renaming my thought and it still is, is to create a list that you then go through one by one just to verify they are proper is that what you'd like or would you prefer I automate?

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Yes, I'm testing from the CLI point as in the shell output above. I'm OK with a few prompts like you had before the recent commits (get, set, rename) but makes sense for most options to be passed in by Click.options or arguments.

As for the renaming aspect, prefer a full list output of proposed renames to scan (dry-run by default) and when not dry-running a one-by-one verify or skip (all from this point) would be useful.

**Comment by AlanBridgeman** [comment]
@gitschatz Makes sense and very doable I won't say a timeline because apparently I'm terribhle at those but I will say soon.

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Cheers!

**Comment by AlanBridgeman** [comment]
@gitschatz I may have to push. But it isn't func_rename (now called rename_files) that does the renames its cli.py that does because the user needs to "approve" the change. I am thonking about playing with this archeticture as cli.py has changed and this excess callback is a bit more complicated then I think it needs to be but for a later time...

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Actually, I made piecemeal edits for Linux as outlined in Issue #5 and was able to test renames on at least pattern so far. So it is running through the prompts and renaming files now.

Now testing more patterns and collecting some notes on discrepancies, which I will post here.

**Comment by OnGitHubSchatz** [comment]
`$ python2.7 cli.py -p '.*/[0-9]+_.*'`
SCN consisting of numbers only, underscore and then wildcard

```
Change ./testdata/files/946062815_open_modernisms.zip into ./testdata/files/Open_modernisms_946062815.zip?:
Change ./testdata/files/1001573653_DAISY202.zip into ./testdata/files/Environmental_biology_1001573653_DAISY202.zip?:
Change ./testdata/files/914216994_Workplace_safety_in_the_foodservice_industry.epub into ./testdata/files/Workplace_safety_in_the_foodservice_industry_914216994.epub?:
Change ./testdata/files/944246088_Good_corporation_bad_corporation.zip into ./testdata/files/Good_corporation_bad_corporation_944246088.zip?:
```

- [x] OK
- [ ] Needs a look

`$ python2.7 cli.py -p '.*/[0-9]*\_[A-Za-z0-9_]*.[a-z]{3,}'`
SCN possible, underscore and then zero or more alpha-numerics+underscores following by a three-char file extension

```
Change ./testdata/files/946062815_open_modernisms.zip into ./testdata/files/Open_modernisms_946062815.zip?: 
Change ./testdata/files/1001573653_DAISY202.zip into ./testdata/files/Environmental_biology_1001573653_DAISY202.zip?: 
Change ./testdata/files/944246088_Good_corporation_bad_corporation.zip into ./testdata/files/Good_corporation_bad_corporation_944246088.zip?:
```

- [x] OK
- [ ] Needs a look 

`$ python2.7 cli.py -p '.*/[a-z0-9]*.zip'`

`Change ./testdata/files/201802141659510237740.zip into ./testdata/files/Un_barbare_en_Chine_nouvelle_201802141659510237740.zip?: `

- [x] OK
- [ ] Needs a look 

`$ python2.7 cli.py -p '.*/[a-z0-9]*.[a-z]{3,}'`

Admittedly could be a tighter pattern but we really need to pass in a target dir here to avoid potential danger.

```
====================================================
|----------------------------------------------------|
| BOOK SUMMARY
| ============
| File Path: ./testdata/files/bcviu000971.pdf
| File Name: bcviu000971.pdf
| Book SCN: None
| Book Title: None
| Book Type: None
|----------------------------------------------------|
bcviu000971.pdf seems to be a bit of a mystory
```

```
$ grep -rn "bcviu000971" testdata/
testdata/BCOpenTextbooks_August2017.xml:203
```
However, this SCN never makes it into my dictionary file. Why does it not parse this one correctly?
- [ ] OK
- [x] Needs a look 

Added edge_cases.xml record set with a single record containing this real world SCN:
e9959a9c-add7-4189-877e-219c6cbc7aa0

`$ python2.7 cli.py -p '.*/[a-z0-9-]{36}.[a-z]{3,}'`
36 lowercase alphanumerics and hyphen and then string or more char extension

```
====================================================
|----------------------------------------------------|
| BOOK SUMMARY
| ============
| File Path: ./testdata/files/e9959a9c-add7-4189-877e-219c6cbc7aa0.zip
| File Name: e9959a9c-add7-4189-877e-219c6cbc7aa0.zip
| Book SCN: None
| Book Title: None
| Book Type: None
|----------------------------------------------------|
e9959a9c-add7-4189-877e-219c6cbc7aa0.zip seems to be a bit of a mystory
Callback Return: {}
```
EDIT: Used a better record file for this one, same as above.

- [ ] OK
- [x] Needs a look

**Comment by AlanBridgeman** [comment]
@gitschatz For the second last (the pdf one) I've figured out that there are two SCNs defined in the Marc XML so I don't account for that right now
```
<ns0:datafield ind1=" " ind2=" " tag="035">
        <ns0:subfield code="a">(Sirsi) bcviu000971</ns0:subfield>
</ns0:datafield>
<ns0:datafield ind1=" " ind2=" " tag="035">
       <ns0:subfield code="a">(OCoLC)898309896</ns0:subfield>
</ns0:datafield>
```
I figured out that if you ran (output.json is the "dictionary" file generated)
```
grep -rn "898309896" output.json
```
then you get a result of
```
output.json:80:{"SCN":"898309896", "title":"Introduction_to_psychology"},
```
But its because within my system they map to the same thing ultimately the last one will always win out right now I could probably implement a more robust solution but I'm not sure how common this is

EDIT: Sorry about the original formating I've used a few different versions of Markdown recently and each works slightly differently

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman OK thanks for finding that, it makes sense.

It is actually somewhat common to have multiple 035s. We have tools that can swap instances and additionally the target SCN is consistent in its order within a given set. 

I think the way of addressing is to include an index parameter to the parsing function for MARC XML, so I can either say I want the 1st 035 field's subfield a per record or the last, etc. What do you think?

**Comment by AlanBridgeman** [comment]
@gitschatz I think thats doable just want to verify.the thought is if multiple exist use rhe first or last (as spevified. If there is one use that. If none generate the new one from a timestamp

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Correct, except index should be an integer so I can pass any position, say 2nd, 4th, etc. I'm OK with index 0 = 1st position to keep it simple. Cheers!

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Have had a chance to look at passing the aforementioned index parameter when parsing SCNs?

**Comment by AlanBridgeman** [comment]
@gitschatz I've been working on it and its turned out to be a bit more complicated then I orginally anticipated. 
The reason for this is the pattern/architecture I decided on for the parser. Because the flow of my parser expects the lowest level component has control by way of callbacka (in other words uses a proximety of the Python decorator pattern) which makes each peice mostly independent of one another. This means I at a higher level have to dynamically recombine results so that it emds up as if they were processed together without this being the case. Which leads to me having to determine the specific circumstances in which to address this needed recombination and moving into the even more complicated because persistant state needs to be done in this weirdly independent way I need to detect of a particular value or set of values is a subset of a another element within the list.

I hope that makes some sense andproves some insight but I'd definitely be hapyy to expand on it if you'd like

**Comment by AlanBridgeman** [comment]
Just finished getting it to work (seemingly). It isn't the cleanist and best solution but it works which is what we want at this point I think

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Back on the case here, pardon for the delay in testing your refactor. I have been using the posix branch with success on the large amount of files we're ingesting.

Two questions:

1) How do you recommend loading the Config settings elsewhere, say in rename_files.py or wherever DEBUG_MODE or HOST_OS are needed? I also want to add in potentially more settings later.

2) When I try to specify a file pattern for rename action I get into a loop that never completes:

```
Would you like to specify a file pattern? [y/N]: y
What file pattern(s) would you like to use?: .*/[a-z0-9]*.zip
Would you like to specify a file pattern? [y/N]: y
What file pattern(s) would you like to use?: ".*/[a-z0-9]*.zip"
Would you like to specify a file pattern? [y/N]: y
What file pattern(s) would you like to use?: '.*/[a-z0-9]*.zip'
Would you like to specify a file pattern? [y/N]:
```

Hints about which regex formatting pattern (or a common default) would be helpful here.

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman nevermind on first part of Question 1, I'm amending with:

```
from config import Config
cfg = Config()
if cfg.HOST_OS == 'Linux':
```

**Comment by AlanBridgeman** [comment]
@gitschatz 2 isn't actually a problem its intentionally a infinite loop you press n to exit the loop. All patterns that you entered are then put together (think of them as ANDing) This isn't the greatest design but it allows me to use the confirm limiting the access and provided people know I feel like its workable.

Also for number 1 I've been working on actually just passing around a single configuration object but that'll probably come some time over the weekend when I've had time to test that and one of my other features that should make this whole thing a lot more scalable

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman OK, thanks for the tip. What's gained from limiting the access?

**Comment by AlanBridgeman** [comment]
@gitschatz I guess it just felt like a more intuitive control to me and came built right into the Click framework. because you can specify essentially infinite patterns to be combined you there had to be a control for the loop and a yes-no question seemed best but perhaps its a wording issue of that question.

Also correction when specifying patterns its OR not AND sorry about that

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Ah, thanks for explaining that - makes sense to me now that you could input multiple patterns one at a time.

Proceeding further, I found two issues after reapplying edits for Linux locally:

```
Do you neeed to generate a dictionary? [y/N]: N
What format to store the dictionary in?: 
```
Still get asked about dictionary even if I decline. Also using the --dictionary dict.json argument throws: 
```
File "cli.py", line 116, in get_records_from_dictionary
    if dictionary_format == 'json':
UnboundLocalError: local variable 'dictionary_format' referenced before assignment
```

Next, if I avoid pre-specified dictionary or decline it and enter Marc XML for metadata parse: 

```
File "/home/schatz/workspace/nnels-pipeline-gadget/rename_files.py", line 528, in _generate_new_file_name
    return_result += book.title + '_' + book.SCN
TypeError: coercing to Unicode: need string or buffer, list found
```

I notice that the find subprocess for XML files is matching on all files and dirs, including git and the Python files themselves - probably I missed something in using posix-friendly amendments?

Here's the DEBUG output:
```
====================================================
Call Summary for get_file_names (rename_files.py)
----------------------------------------------------
Patterns: [u'.*/[a-z0-9]*.zip']
Workspace: .
====================================================
====================================================
Call Summary for combine_regex (funcs.py)
----------------------------------------------------
Patterns: [u'.*/[a-z0-9]*.zip']
Prefix (Whole): None
Suffix (Whole): None
Prefix (Each): None
Suffix (Each): None
===================|================================
['find', '.', '-regextype posix-extended', '-regex', u"'.*/[a-z0-9]*.zip'"]
The filename seems to be unreadable (has no length)
```

**Comment by AlanBridgeman** [comment]
@gitschatz So the first (and second kinda) aren't actually a (major) issue. Its another one of those situations where I've realized my choice of wording probably doesn't work its just asking the format of the file your importing (JSON, txt, csv, etc..) so that I know which format the file  is stored in for parsing reasons.

The other issue I'm looking into because that seems more problematic. Though in relation to your question of why its looking through your git etc... its looking at the . (current directory) I can't remember if this is something I've made available to the CLI yet if not its just a matter of adding a prompt and argument

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman OK - yes last issue is the major one, cheers.

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman I'm running into some issues on the latest that appear to be due to empty test files—fair enough I will use real samples in those places or add a check for file emptiness.

However there is this message where non-EPUBs are being operated on with zip command I believe:

```
Call Summary for __init__ (Metadata_XML_Parser) 
----------------------------------------------------
Self: <Parsers.OPF_Parser.OPF_Parser object at 0x7ff8f86c9b10>
XML File List: None
====================================================
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./testdata/files/9781553803003.epub or
        ./testdata/files/9781553803003.epub.zip, and cannot find ./testdata/files/9781553803003.epub.ZIP, period.
[./testdata/files/9781553803003.epub]
```
What's going on here?

**Comment by AlanBridgeman** [comment]
@gitschatz Basically when I'm parsing OPF I delegate extracting the file from the zip file to unzip because compressed files have lots of gotchas in my experience that I just wanted to mitigate so one of the side effects is that this uses the manifest file contained in the META-INF directory in every valid zip file that tells programs what files are contained in the zip their name, their location, etc.. etc... Does that make sense?

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Aye, makes sense - I am definitely leaning on blank or dummy files too much in testing but I see the need for validating the format in real life. I will just need to suppress this message.

**Comment by AlanBridgeman** [comment]
@gitschatz yeah, I want to write a work around or otherwise a test case type scenerio the issue being its a subprocess call to unzip so uts more complicated then just an if statemenr say

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Next question: regarding the Click options added to  [/commands/rename.py](https://github.com/BCLibCoop/nnels-pipeline-gadget/blob/develop/commands/rename.py#L35) , I know this is called when selecting an action in the cli.py entry point but how do I pass those cli switches here? I can't seem to call directly.

**Comment by AlanBridgeman** [comment]
@gitschatz i'm not 100% clear on what you mean but this question is starting to get into the deep end so I'll give you the short answer and if your still not sure I can start to get into the more detailed stuff.

So, essentially Click has commands and subcommands when a subcmmand is called it technically passes through the command first so that you can do certain processing shared by all subcommands but once rhats all done it hands over control to the subcommand unfortunately because of the way things work its not as simple as just calling the subcommand so you need what they call a Context which then serves as your storage between your command and subcommand. Because I do "lazy loading" this becomes even more complicated but I'll leave that for the long answer.

Is that making any sense?

**Comment by OnGitHubSchatz** [comment]
@AlanBridgeman Thanks for the reminder of the subcommand context, I re-read the docs on it and its clear how to pass in subcommand options now. I expected it to infer from --action rename but I needed:
`$ ./cli.py --action rename rename --folder testdata/files`

Cheers - I think this issue is complete (finally)

**Comment by AlanBridgeman** [comment]
@gitschatz that makes sense though specifying --action in that case s redundent its mostly if you want to specify the action but be prompted for the other stuff/use the defaults
